### ISSUE TITLE
No license used

### ISSUE THREAD

**Issue by ragkousism** [jwilberding/bcp#18]
As I have noticed there is no license used in the project. Shouldn't it be more appropriate to use one in order to protect the project from any unwanted  implications ?
And as a free software supporter I suggest using GNU GPL license

**Comment by jwilberding** [comment]
I would be fine with GPLv3. Would you be willing to submit a pull request to add it?

**Comment by ragkousism** [comment]
Of course, I will do it the moment I return to my computer
