### ISSUE TITLE
Fix os/arch dependency issues

### ISSUE THREAD

**Issue by jwilberding** [jwilberding/bcp#7]
Thanks to jbester:

1) The code assumes both the client and the server have the same endian. This can be issue since a uint32 is used for both the synchronization code (BCP_CODE) and the port. This can easily fixed with htonl/ntohl conversions.

2) it assumes both the client and the server define int to be the same size (may or may not be true based on compiler/processor/OS combinations). If you use stdint definitions, this typically won't be an issue

**Comment by jwilberding** [comment]
Fix by 5049e864842d0cf747ba0644cef23ec0c8954a25

**Comment by jbester** [comment]
Commit 5049e86 fixes the issue with respect to file name length.  But does not address port or BCP_CODE in the synchronization packet.

**Comment by jwilberding** [comment]
Oops, those are fixed with c6ba7985d9e6dfd05445b31593c4024e9fe4515f
